baseURL = "https://invisement.com/"
languageCode = "en-us"
title = "inVisement"
theme = "../theme"
#themesDir = ".themes"
#disqusShortname = "clientrelationship" # delete this to disable disqus comments
googleAnalytics = ""
uglyurls = true

pygmentsUseClassic = false
pygmentsUseClasses = false
linenos = "table"
pygmentsCodefences = true
pygmentsStyle = "perldoc"
#pygmentsCodefencesGuessSyntax = true

[pygmentsOptions]
    linenos = "table"

[taxonomies]
  tag = "tags"

[params]
    author = "inVisement"
    profilePic = "/images/logo.jpg"
    description = "<img src='images/corp-banner.jpg'><br>\
    Fundamental Data Provider to Financial Firms<br><br> \
    <a href='https://data.invisement.com?q-stmt/AAPL.csv'> Available Data Sets </a><br>\
    <a href='/tags/api'>How To Use</a><br>\
    <a href='/tags/blog'>Blog</a>"
    githubUsername = "invisement"
    accent = "blue"
    showBorder = true
    backgroundColor = "white"
    font = "Roboto" # should match the name on Google Fonts!

[[menu.main]]
    url = "https://data.invisement.com?q-stmt/AAPL.csv"
    name = "Data"
    weight = 10

[[menu.main]]
    url = "/tags/blog/"
    name = "Blog"
    weight = 30

[[menu.main]]
    url = "/tags/api"
    name = "API Docs"
    weight = 20

[[menu.main]]
    url = "/tags/about"
    name = "About us"
    weight = 40

[[menu.main]]
    url = "/tags"
    name = "tags"
    weight = 50


# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[menu.icon]]
    url = "mailto:client@invisement.com"
    name = "envelope-o"
    weight = 10

[[menu.icon]]
    url = "https://github.com/username/"
    name = "github"
    weight = 20
