
theme = "docuapi"

# theme = "amp"
# theme = "hugo-theme-learn"

# theme = "mainroad" # simple beautiful for posts
# theme = "blackburn" #blog with side

themesdir = ".themes"
contentDir = "content"
publishDir = "www"
dataDir = "hugo-data"
#languageCode = "en-us"
baseURL = "http://invisement.com/"
title = "inVisement"
disableKinds = ["404", "section", "taxonomyTerm","taxonomy","RSS"] #"page", "home", "section", "taxonomy", "taxonomyTerm", "RSS", "sitemap", "robotsTXT", "404"

sectionPagesMenu = "main"

###################### FOR docuapi THEME
# Code higlighting settings
pygmentsCodefences = true
#pygmentsCodeFencesGuesSsyntax = false
# pygmentsOptions = ""
pygmentsStyle = "rrt"
# The monokai stylesheet is included in the base template.
#pygmentsUseClassic = true
#pygmentsUseClasses=true

[params]
search = true

# Configure the language example tabs.
[[params.language_tabs]]
key = "md"
name = "HTML"
[[params.language_tabs]]
key = "js"
name = "JS"
[[params.language_tabs]]
key = "python"
name = "Python"
[[params.language_tabs]]
key = "r"
name = "R"
[[params.language_tabs]]
key = "sheets"
name = "Google Sheets"
[[params.language_tabs]]
key = "excel"
name = "Excel"


